version: '3.8'

services:

  pyhouse-frontend:
    build:
      context: ../../pyhouse-service/pyhouse-frontend
      dockerfile: prod.Dockerfile
    image: pyhouse-frontend:0.0.1
    volumes:
      - /home/app/node_modules
    
    labels:
      - "traefik.http.routers.pyhouse-frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.pyhouse-frontend.service=pyhouse-frontend"
      - "traefik.http.routers.pyhouse-frontend.entrypoints=web"
      - "traefik.http.services.pyhouse-frontend.loadbalancer.server.port=80"

  auth-backend:
    build:
      context: ../../auth-service/auth-backend
      dockerfile: prod.Dockerfile
    image: auth-backend:0.0.1
    

  
    
    labels:
      - "traefik.http.routers.auth-backend.rule=PathPrefix(`/auth/api`)"
      - "traefik.http.routers.auth-backend.service=auth-backend"
      - "traefik.http.routers.auth-backend.entrypoints=web"
      - "traefik.http.services.auth-backend.loadbalancer.server.port=8000"
    secrets:
      - all_db_user.txt
      - all_db_password.txt


secrets:
  all_db_user.txt:
    file: ../../secret/dev/all_db_user.txt
  all_db_password.txt:
    file: ../../secret/dev/all_db_password.txt
