version: '3.8'

services:
  
  admin-shell:
    build: ../../admin-shell
    image: admin-shell:0.0.1
   


  manager-backend:
    build:
      context:  ../../manager-service/manager-backend
      dockerfile: prod.Dockerfile
    image: manager-backend:0.0.1
    
    volumes:
   
      - /var/run/docker.sock:/var/run/docker.sock
      - container-file:/container-file

    environment:
      - app_mode=prod_without_tls
    
    labels:
      - "traefik.http.routers.manager-backend.rule=PathPrefix(`/manager/api`)"
      - "traefik.http.routers.manager-backend.service=manager-backend"
      - "traefik.http.routers.manager-backend.entrypoints=web"
      - "traefik.http.services.manager-backend.loadbalancer.server.port=8000"
    secrets:
      - all_db_user.txt
      - all_db_password.txt


  coredb: 
    image: mongo:5.0.9-focal
   
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/all_db_user.txt
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/all_db_password.txt

    secrets:
      - all_db_user.txt
      - all_db_password.txt
    
    volumes:
      - coredb-volume:/data/db

    ports:
      - 27017:27017

volumes:
  coredb-volume:
  container-file:

secrets:
  all_db_user.txt:
    file:  ../../secret/dev/all_db_user.txt
  all_db_password.txt:
    file:  ../../secret/dev/all_db_password.txt
