version: '3.8'

services:

  pyhouse-frontend:
    build:
      context: ../../pyhouse-service/pyhouse-frontend
      dockerfile: dev.Dockerfile
    image: pyhouse-frontend:0.0.1
    volumes:
      - ${ROOT_PROJECT}/pyhouse-service/pyhouse-frontend/app:/home/app
      - /home/app/node_modules
      - ${ROOT_PROJECT}/.vscode-server/vscode-pyhouse-frontend:/root/.vscode-server

    labels:
      - "traefik.http.routers.pyhouse-frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.pyhouse-frontend.service=pyhouse-frontend"
      - "traefik.http.routers.pyhouse-frontend.entrypoints=web"
      - "traefik.http.services.pyhouse-frontend.loadbalancer.server.port=80"

  auth-backend:
    build:
      context: ../../auth-service/auth-backend
      dockerfile: dev.Dockerfile
    image: auth-backend:0.0.1
    
    env_file:
      - ../../auth-service/auth-backend/dev.env
    volumes:
      - ${ROOT_PROJECT}/auth-service/auth-backend/src:/home/src
      - ${ROOT_PROJECT}/.vscode-server/vscode-auth-backend:/root/.vscode-server

    
    labels:
      - "traefik.http.routers.auth-backend.rule=PathPrefix(`/auth/api`)"
      - "traefik.http.routers.auth-backend.service=auth-backend"
      - "traefik.http.routers.auth-backend.entrypoints=web"
      - "traefik.http.services.auth-backend.loadbalancer.server.port=8000"
    secrets:
      - all_db_user.txt
      - all_db_password.txt


secrets:
  all_db_user.txt:
    file: ../../secret/dev/all_db_user.txt
  all_db_password.txt:
    file: ../../secret/dev/all_db_password.txt
