version: '3.8'

services:
  # manager-frontend:
  #   build:
  #     context: ../../manager-service/manager-frontend
  #     dockerfile: dev.Dockerfile
  #   image: manager-frontend:0.0.1
  #   volumes:
  #     - ../../manager-service/manager-frontend/app:/home/app
  #     - /home/app/node_modules
  #     - ../../.vscode-server/.vscode-manager-frontend:/root/.vscode-server

  #   labels:
  #     - "traefik.http.routers.manager-frontend.rule=PathPrefix(`/`)"
  #     - "traefik.http.routers.manager-frontend.service=manager-frontend"
  #     - "traefik.http.routers.manager-frontend.entrypoints=web"
  #     - "traefik.http.services.manager-frontend.loadbalancer.server.port=80"


  manager-backend:
    build:
      context: ../../manager-service/manager-backend
      dockerfile: dev.Dockerfile
    image: manager-backend:0.0.1
    
    volumes:
      - ../../manager-service/manager-backend/src:/app/src
      - ../../.vscode-server/vscode-manager-backend:/root/.vscode-server


      - /var/run/docker.sock:/var/run/docker.sock
      - container-file:/container-file


    
    labels:
      - "traefik.http.routers.manager-backend.rule=PathPrefix(`/manager/api`)"
      - "traefik.http.routers.manager-backend.service=manager-backend"
      - "traefik.http.routers.manager-backend.entrypoints=web"
      - "traefik.http.services.manager-backend.loadbalancer.server.port=8000"
    secrets:
      - all_db_user.txt
      - all_db_password.txt


  coredb: 
    image: mongo:5.0.9-focal
   
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/all_db_user.txt
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/all_db_password.txt

    secrets:
      - all_db_user.txt
      - all_db_password.txt
    
    volumes:
      - coredb-volume:/data/db

    ports:
      - 27017:27017

volumes:
  coredb-volume:
  container-file:

secrets:
  all_db_user.txt:
    file: ../../secret/dev/all_db_user.txt
  all_db_password.txt:
    file: ../../secret/dev/all_db_password.txt
